import asyncio
from datetime import datetime
from uuid import uuid4
from db import db, create_indexes
from auth import get_password_hash
from models import Role, ReportStatus

async def seed():
    print("🌱 Seeding Aroha v2 Dummy Data...")
    await create_indexes()

    # 1. Create Doctors
    doctors_data = [
        {"email": "dr.smith@aroha.com", "name": "Dr. Smith"},
        {"email": "dr.jones@aroha.com", "name": "Dr. Jones"},
    ]
    
    doctor_ids = []
    for d in doctors_data:
        did = str(uuid4())
        user_doc = {
            "email": d["email"],
            "password_hash": get_password_hash("password123"),
            "role": Role.DOCTOR.value,
            "doctor_id": did,
            "created_at": datetime.utcnow()
        }
        res = await db.users.insert_one(user_doc)
        uid = str(res.inserted_id)
        
        await db.doctors.insert_one({
            "user_id": uid,
            "doctor_id": did,
            "name": d["name"],
            "email": d["email"],
            "created_at": datetime.utcnow()
        })
        doctor_ids.append(did)
        print(f" - Created Doctor: {d['email']}")

    # 2. Create Patients
    patients_data = [
        "alice@example.com", "bob@example.com", "charlie@example.com"
    ]
    
    patient_ids = []
    for email in patients_data:
        pid = str(uuid4())
        user_doc = {
            "email": email,
            "password_hash": get_password_hash("password123"),
            "role": Role.PATIENT.value,
            "patient_id": pid,
            "created_at": datetime.utcnow()
        }
        res = await db.users.insert_one(user_doc)
        uid = str(res.inserted_id)
        
        await db.patients.insert_one({
            "user_id": uid,
            "patient_id": pid,
            "email": email,
            "created_at": datetime.utcnow()
        })
        patient_ids.append(pid)
        print(f" - Created Patient: {email}")

    # 3. Create Assignments
    for i, pid in enumerate(patient_ids):
        did = doctor_ids[i % len(doctor_ids)]
        await db.doctor_patient_assignments.insert_one({
            "doctor_id": did,
            "patient_id": pid,
            "created_at": datetime.utcnow()
        })
    print(" - Created Doctor-Patient Assignments")

    # 4. Create Dummy Reports
    for pid in patient_ids:
        report_doc = {
            "patient_id": pid,
            "uploaded_by": "system-seed",
            "status": ReportStatus.PARSED.value,
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow()
        }
        res = await db.reports.insert_one(report_doc)
        rid = res.inserted_id
        
        await db.report_analysis.insert_one({
            "report_id": rid,
            "summary": "Baseline healthy report generated by seeder.",
            "severity_score": 10,
            "risk_level": "Low",
            "created_at": datetime.utcnow()
        })
    
    print("✅ Seeding complete!")

if __name__ == "__main__":
    asyncio.run(seed())
